---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - python3
      - python3-pip
      - git
      - curl
      - wget
      - net-tools
      - software-properties-common
    state: present
    update_cache: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest

